#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"
#include "levels/yajima/areas/1/1/model.inc.c"
#include "levels/yajima/areas/2/1/model.inc.c"
#include "levels/yajima/areas/3/1/model.inc.c"
//#include "levels/yajima/areas/1/2/model.inc.c"
//#include "levels/yajima/areas/1/3/model.inc.c"
//#include "levels/yajima/areas/1/4/model.inc.c"
#include "levels/yajima/areas/1/collision.inc.c"
#include "levels/yajima/areas/2/collision.inc.c"
#include "levels/yajima/areas/3/collision.inc.c"

