#include "motos_basedata_A.inc.c"
#include "motos_carry.inc.c"
#include "motos_carry_run.inc.c"
#include "motos_carry_start.inc.c"
#include "motos_down_recover.inc.c"
#include "motos_down_stop.inc.c"
#include "motos_pitch.inc.c"
#include "motos_safe_down.inc.c"
#include "motos_wait.inc.c"
#include "motos_walk.inc.c"

