// 0x16000388
const GeoLayout warp_pipe_geo[] = {
   GEO_CULLING_RADIUS(700),
   GEO_OPEN_NODE(),
    GEO_SCALE(0x00, 32768),
   GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, RCP_dokan),
		GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
