COURSE_ACTS(COURSE_BOB, _(" 1 BATTLE FIELD"),
       _("CHUCKING ON THE SUMMIT")     , _("FOOTRACE WITH KOOPA THE QUICK") , _("BEHIND BIG CHOMP'S GATES"),
       _("SHOOT TO THE ISLAND IN THE SKY")          , _("MARIO WINGS TO THE SKY")        , _("FIND THE 8 RED COINS"))

COURSE_ACTS(COURSE_WF, _(" 2 CASTLE2"),
       _("TO THE TOP OF THE FORTRESS")        , _("SHOOT INTO THE WILD BLUE")    , _("STAR ON THE FLOATING ISLE"),
       _("TEAR DOWN THE TOWER"), _("TOP OF THE WORLD")    , _("LOCATE THE 8 RED COINS"))

COURSE_ACTS(COURSE_JRB, _(" 3 SUNKENSHIP"),
       _("PLUNDER IN THE SUNKEN SHIP")    , _("CAN THE EEL COME OUT TO PLAY?") , _("TREASURE OF THE OCEAN CAVE"),
       _("RED COINS ON THE SHIP AFLOAT")  , _("BLAST TO THE STONE PILLAR")     , _("THROUGH THE JET STREAM"))

COURSE_ACTS(COURSE_CCM, _(" 4 SNOW MOUNTAIN"),
       _("LI'L PENGUIN LOST")             , _("SNOWMAN'S LOST HIS HEAD")             , _("WALL KICKS WILL WORK"),
       _("FROSTY SLIDE FOR 8 RED COINS")  , _("SLIP SLIDIN' AWAY")       , _("BIG PENGUIN RACE"))

COURSE_ACTS(COURSE_BBH, _(" 5 GHOST HOUSE"),
       _("GO ON A GHOST HUNT")            , _("SCOWERING THE SEWERS") , _("SECRET OF THE TRAP-DOOR"),
       _("KEY TO A PUZZLIN' BOOKSHELF")          , _("ENTRANCE TO THE BALCONY")             , _("SEEK THE 8 RED COINS"))

COURSE_ACTS(COURSE_HMC, _(" 6 CAVE MAZE"),
       _("SWIMMING BEAST IN THE CAVERN")  , _("METAL-HEAD MARIO CAN MOVE!")       , _("NAVIGATING THE TOXIC MAZE"),
       _("WATCH FOR ROLLING ROCKS")     , _("A-MAZE-ING EMERGENCY EXIT")     , _("ELEVATE FOR 8 RED COINS"))

COURSE_ACTS(COURSE_LLL, _(" 7 VOLCANO"),
       _("BOIL THE BIG BULLY")            , _("TOSSING OFF TOSSYA")             , _("SOLVE THE PUZZLE WITH 15 PIECES"),
       _("SHELL SURFIN' FOR 8 RED COINS")           , _("HOT-FOOT-IT INTO THE VOLCANO")  , _("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 DESERT PYRAMID"),
       _("SHINING ATOP THE PYRAMID") , _("IN THE TALONS OF THE BIG BIRD")      , _("STAND TALL ON THE FOUR PILLARS"),
       _("INSIDE THE ANCIENT PYRAMID"), _("8 RED COINS IN THE PYRAMID")   , _("FIGHTING HAND-TO-HAND"))

COURSE_ACTS(COURSE_DDD, _(" 9 SUBMARINE"),
       _("BOARD BOWSER'S SUB")            , _("CHESTS IN THE CURRENT")        ,_("THROUGH THE JET STREAM")
	   , _("POLE-JUMPING FOR RED COINS")        , _("THE MANTA RAY'S REWARD")        , _("SINKING LIKE A ROCK"))

COURSE_ACTS(COURSE_SL, _("10 SNOWMAN"),
       _("SNOWMAN'S BIG HEAD")            , _("IN THE DEEP FREEZE")          , _("ANOTHER LI'L PENGUIN LOST"),
       _("OVER THE SNOWMAN'S BIG HEAD")  , _("SHELL SHREDDIN' FOR RED COINS") , _("ICE SEE YA TOSSYA"))

COURSE_ACTS(COURSE_WDW, _("11 WATER TOWN"),
       _("SHOCKING ARROW LIFTS!")         , _("TOP O' THE TOWN")               , _("SECRETS IN THE SHALLOWS & SKY"),
       _("EXPRESS ELEVATOR--HURRY UP!")   , _("GO TO TOWN FOR RED COINS")      , _("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 MONKEY MOUNTAIN"),
       _("SCALE THE MOUNTAIN")            , _("BREATHTAKING VIEW FROM BRIDGE")    , _("MYSTERIOUS MOUNTAINSIDE"),
       _("BLAST TO THE LONELY MUSHROOM")       , _("MYSTERY OF THE MONKEY CAGE") , _("MOUNTAIN SLIDE FOR 8 RED COINS"))

COURSE_ACTS(COURSE_THI, _("13 BIG & SMALL"),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("A MINIATURE ISLE"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 CLOCK TOWER"),
        _("GET A HAND")				,_("ROLL INTO THE CAGE")				, _("THE PIT AND THE PENDULUMS"),
       _("TIMED JUMPS ON MOVING BARS"), 	_("CLOCKING IN AT THE TOP")    , _("STOP TIME FOR RED COINS"))

SECRET_STAR(COURSE_BITDW, _("   PURGATORY"))
SECRET_STAR(COURSE_BITFS, _("   HELL"))
SECRET_STAR(COURSE_BITS, _("   HEAVEN"))
SECRET_STAR(COURSE_PSS, _("   MINI SLIDE"))
SECRET_STAR(COURSE_COTMC, _("   IN THE FALL"))
SECRET_STAR(COURSE_TOTWC, _("   FLYING MARIO"))
SECRET_STAR(COURSE_VCUTM, _("   MINIATURE MOAT"))
SECRET_STAR(COURSE_WMOTR, _("   BLUE SKY"))
SECRET_STAR(COURSE_SA, _("   FISH TANK"))
SECRET_STAR(COURSE_CASTLE, _("    EXTRA: HIDDEN CASTLE"))
SECRET_STAR(COURSE_DONJON, _("    EXTRA: FORGOTTEN WALLS"))
SECRET_STAR(COURSE_ENDING, _("    DELICIOUS CAKE"))
CASTLE_SECRET_STARS(_("   CASTLE SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE CASTLE'S SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
