// 0x0F00066C
const GeoLayout sun_geo_neutral[] = {
GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 400),
   GEO_OPEN_NODE(),
     GEO_BILLBOARD(),
       GEO_OPEN_NODE(),
	   	GEO_SWITCH_CASE(8, geo_switch_anim_state),
		GEO_OPEN_NODE(),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_0),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_0),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_1),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_1),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_2),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_2),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_3),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_3),
		 GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
const GeoLayout sun_geo_angry[] = {
GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 400),
   GEO_OPEN_NODE(),
     GEO_BILLBOARD(),
       GEO_OPEN_NODE(),
	   	GEO_SWITCH_CASE(8, geo_switch_anim_state),
		GEO_OPEN_NODE(),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_0),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_0),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_1),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_1),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_2),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_2),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_3),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_angry_3),
		 GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
const GeoLayout sun_geo_neutral_angry[] = {
GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 400),
   GEO_OPEN_NODE(),
     GEO_BILLBOARD(),
       GEO_OPEN_NODE(),
	   	GEO_SWITCH_CASE(8, geo_switch_anim_state),
		GEO_OPEN_NODE(),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_0),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_0),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_1),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_1),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_2),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_2),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_3),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_3),
		 GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
const GeoLayout sun_geo_angry_neutral[] = {
GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 400),
   GEO_OPEN_NODE(),
     GEO_BILLBOARD(),
       GEO_OPEN_NODE(),
	   	GEO_SWITCH_CASE(8, geo_switch_anim_state),
		GEO_OPEN_NODE(),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_4),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_4),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_5),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_5),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_6),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_6),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_7),
		 GEO_DISPLAY_LIST(LAYER_ALPHA, angry_sun_seg8_dl_netural_angry_7),
		 GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
